import sys, os
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # repo root
sys.path.insert(0, os.path.join(ROOT, "scripts"))
import dbutil as db
R = db.record
A24CA = db.app("2024", "CA", "Sport Touring", "6MT and CVT (table covers both)")
A24US = db.app("2024", "US", "Sport Touring", "6MT and CVT", notes="US spec table, Sport Touring column (4th of LX/Sport/EX-L/Sport Touring)")
A22US_ALL = db.app("2022", "US", "all Civic trims (Sedan and Hatchback)", "all", engine="1.5T and 2.0", notes="Press kit statement covers all 2022 Civic trims")
A22US_H = db.app("2022", "US", "Sport Touring (hatchback)", "all")
A22CA = db.app("2022", "CA", "Sport Touring", "6MT and CVT")
MYCHK = "Model-year check: 2024 Honda Canada and US spec tables list the same tire size, 18-in wheels and brake layout as 2022; no change found."

SRC = {
 "d7:hondanews-ca-2024-hatch-specs": dict(title="2024 Honda Civic Hatchback Specifications (April 4, 2024)", url="https://hondanews.ca/en-CA/releases/release-1128768177ab00a73471b1938c152ddf-2024-honda-civic-hatchback-specifications", publisher="Honda Canada (newsroom)", cls="A", applicability="2024 Civic Hatchback Sport and Sport Touring, Canada", cache_file="cache/pages/22157798d6e48e1c.txt"),
 "d7:hondainfocenter-us-2024-hatch-specs": dict(title="2024 Civic Hatchback Specifications (Honda Info Center)", url="https://www.hondainfocenter.com/2024/Civic-Hatchback/Feature-Guide/Civic-Hatchback-Specifications/", publisher="American Honda Motor Co.", cls="A", applicability="2024 Civic Hatchback LX/Sport/EX-L/Sport Touring, US", cache_file="cache/pages/b67f7f855816944e.txt"),
 "d7:hondainfocenter-us-2024-wheels": dict(title="Wheels and Tires (2024 Civic Hatchback feature guide)", url="https://www.hondainfocenter.com/2024/Civic-Hatchback/Feature-Guide/Exterior-Features/Wheels-and-Tires/", publisher="American Honda Motor Co.", cls="A", applicability="2024 URL, page title reads 2023; US hatchback lineup", cache_file="cache/pages/d32ce19bfbb50617.txt"),
 "d7:hondaca-2022-hatch-specpdf": dict(title="2022 Civic Hatchback header spec sheet (PDF)", url="https://www.honda.ca/Content/honda.ca/86525d2a-11fa-4527-8754-5ed987f3510e/ModelPage_Downloads/028382_01_22MY_Civic_Hatchback_HeaderSpec_EN_V2_hires.pdf", publisher="Honda Canada", cls="A", access_method="pdf", applicability="2022 Civic Hatchback LX/Sport/Sport Touring, Canada", cache_file="cache/pdf/d3af82f728361fd5.pdf"),
 "d7:hondanews-us-2022-hatch-presskit": dict(title="2022 Honda Civic Hatchback Press Kit (September 29, 2021)", url="https://hondanews.com/en-US/releases/release-20c92b0d934f0bc63982bd3eee0149e9-2022-honda-civic-hatchback-press-kit", publisher="American Honda (hondanews.com)", cls="A", access_method="rendered", applicability="2022 Civic Hatchback, US", cache_file="cache/pages/9964dff4363f93bf.txt"),
 "d7:hondapartsnow-2024-rims": dict(title="Genuine 2024 Honda Civic Rims", url="https://www.hondapartsnow.com/oem-2024-honda-civic-rims.html", publisher="HondaPartsNow (Genuine Parts Now, Inc., Honda parts retailer)", cls="C", applicability="2024 Civic all bodies, US parts catalog data", cache_file="cache/pages/8e7d6cb35e32b697.txt"),
 "d7:hondapartsnow-2022-rims": dict(title="Genuine 2022 Honda Civic Rims", url="https://www.hondapartsnow.com/oem-2022-honda-civic-rims.html", publisher="HondaPartsNow (Genuine Parts Now, Inc., Honda parts retailer)", cls="C", applicability="2022 Civic all bodies, US parts catalog data", cache_file="cache/pages/ce063aa3d9e29654.txt"),
 "d7:hondapartsnow-2024-calipers": dict(title="Genuine 2024 Honda Civic Brake Caliper", url="https://www.hondapartsnow.com/oem-2024-honda-civic-brake_caliper.html", publisher="HondaPartsNow (Genuine Parts Now, Inc., Honda parts retailer)", cls="C", applicability="2024 Civic all bodies, US parts catalog data", cache_file="cache/pages/b5ec7718f9eca09d.txt"),
 "d7:kamispeed-11thgen-fitment": dict(title="2022 Civic 11th Gen wheel fitment (blog)", url="https://www.kamispeed.com/blogs/news/2022-civic-11th-gen-wheel-fitment", publisher="Kami Speed (aftermarket wheel/parts retailer)", cls="C", applicability="2022+ Civic generic ('factory 18\" wheels'); trim not stated", cache_file="cache/pages/b2fa02ebafd3854d.txt"),
 "d7:tirepressure-2024-civic": dict(title="2024 Honda Civic Tire Pressure", url="https://tirepressure.com/2024-honda-civic-tire-pressure", publisher="tirepressure.com (aggregator)", cls="C", applicability="2024 Civic, US, by tire size and trim", cache_file="cache/pages/365ef712f5d6b5f1.txt"),
}

def mk(domain, title, used):
    p = db.path_for(domain)
    if os.path.exists(p): os.remove(p)
    d = db.load_or_new(domain, title)
    for s in used:
        kw = dict(SRC[s]); db.add_source(d, s, kw.pop("title"), kw.pop("url"), kw.pop("publisher"), kw.pop("cls"), **kw)
    return d

# ------------------------------------------------------------------ wheels
w = mk("wheels", "Wheels", ["d7:hondanews-ca-2024-hatch-specs", "d7:hondainfocenter-us-2024-hatch-specs", "d7:hondainfocenter-us-2024-wheels", "d7:hondaca-2022-hatch-specpdf", "d7:hondanews-us-2022-hatch-presskit", "d7:hondapartsnow-2024-rims", "d7:hondapartsnow-2022-rims", "d7:kamispeed-11thgen-fitment"])
add = lambda d, k, desc, u, imp, r: db.add_candidate(d, k, desc, u, imp, r)
add(w, "wheels.diameter", "Wheel (rim) nominal diameter", "m", "high", R(printed=(18, "in"), source_id="d7:hondanews-ca-2024-hatch-specs", locator="CHASSIS table, Sport Touring column", evidence='18" aluminum-alloy wheels (machined with black inserts)', as_printed='18"', applicability=A24CA, confidence="high"))
add(w, "wheels.diameter", "Wheel (rim) nominal diameter", "m", "high", R(printed=(18, "in"), source_id="d7:hondainfocenter-us-2024-hatch-specs", locator="Engine & Chassis table, row 'Wheels', 4th column", evidence="Wheels 16 in Alloys 18 in Alloys 17 in Alloys 18 in Alloys", as_printed="18 in Alloys", applicability=A24US, confidence="high"))
add(w, "wheels.width", "Wheel rim width", "m", "high", R(printed=(8, "in"), cls="C", source_id="d7:hondapartsnow-2024-rims", locator="listing 42700-T20-A31", evidence="2024 Honda Civic 18x8 Hatchback Sport Touring Alloy Wheels Part Number: 42700-T20-A31 … Other Name : W-DISK (18X8J); Wheel, Alloy … Fits the following 2024 Honda Civic Submodels: 5 Door 1.5T Sport Touring | 6MT, CVT", as_printed="18X8J", applicability=db.app("2024", "US", "Sport Touring", "6MT, CVT", notes="Honda part name W-DISK (18X8J) from parts catalog data"), confidence="high", notes="Honda part designation 18X8J = 18 in diameter, 8.0 in width, J flange. Same part number listed for 2022 and 2023 5 Door Sport Touring. Canadian part number not checked (Honda Canada parts catalog not opened)."))
add(w, "wheels.part_number", "Honda part number, Sport Touring 18-in wheel", "text", "low", R(value="42700-T20-A31", unit="text", cls="C", source_id="d7:hondapartsnow-2024-rims", locator="listing 42700-T20-A31", evidence="2024 Honda Civic 18x8 Hatchback Sport Touring Alloy Wheels Part Number: 42700-T20-A31", as_printed="42700-T20-A31", applicability=db.app("2024", "US", "Sport Touring", "6MT, CVT"), confidence="high", notes="Same number on the 2022 listing ('Fits ... 5 Door Sport Touring | 6MT, CVT'). The Sport hatch wheel is a different part (42700-T20-A72 / -T47-A71)."))
add(w, "wheels.part_number", "Honda part number, Sport Touring 18-in wheel", "text", "low", R(value="42700-T20-A31", unit="text", cls="C", source_id="d7:hondapartsnow-2022-rims", locator="listing 42700-T20-A31", evidence="2022 Honda Civic 18x8 Hatchback Sport Touring Alloy Wheels Part Number: 42700-T20-A31", as_printed="42700-T20-A31", applicability=db.app("2022", "US", "Sport Touring", "6MT, CVT"), confidence="high"))
add(w, "wheels.finish", "Wheel finish", "text", "medium", R(value="machined face with black inserts (2024 CA wording); 2022: 'machined-tinted with black inserts' / 'dark clear-coated machined face and Berlina Black inserts'", unit="text", source_id="d7:hondanews-ca-2024-hatch-specs", locator="CHASSIS table", evidence='18" aluminum-alloy wheels (machined with black inserts)', as_printed="machined with black inserts", applicability=A24CA, confidence="high"))
add(w, "wheels.finish", "Wheel finish", "text", "medium", R(value="dark clear-coated machined face, Berlina Black inserts", unit="text", source_id="d7:hondanews-us-2022-hatch-presskit", locator="Exterior Design: 'Four New Wheel Designs'", evidence="On the top-line Sport Touring is an upscale 18-inch split 5-spoke design with a dark clear-coated machined face and Berlina Black inserts.", as_printed="dark clear-coated machined face and Berlina Black inserts", applicability=A22US_H, confidence="high", notes="Canada 2022 spec PDF: '18\" aluminum-alloy wheels (machined-tinted with black inserts)'. Same part number 2022-2024 per parts catalog, so design unchanged."))
add(w, "wheels.spoke_design", "Spoke design", "text", "medium", R(value="split 5-spoke, unique to Sport Touring", unit="text", source_id="d7:hondanews-us-2022-hatch-presskit", locator="Exterior Design: 'Four New Wheel Designs'", evidence="On the top-line Sport Touring is an upscale 18-inch split 5-spoke design with a dark clear-coated machined face and Berlina Black inserts.", as_printed="split 5-spoke", applicability=A22US_H, confidence="high", notes="2024 US feature guide: 'Civic Sport Touring Hatchback shows off its own unique 18-inch alloy wheel design'."))
add(w, "wheels.offset", "Wheel offset (ET)", "m", "high", R(printed=(50, "mm"), cls="C", source_id="d7:kamispeed-11thgen-fitment", locator="article body, first paragraph", evidence='If you\'re running the factory 18" wheels, then you have an 18x8" wheel with a +50 offset.', as_printed="+50", applicability=db.app("2022+", "US", "unspecified 18-in factory wheel (Sport/Si/ST not distinguished)", "unspecified", body="sedan/hatchback unspecified"), confidence="low", how_to_measure="Read the ET stamping on the back of a wheel spoke/hub face, or measure hub-face to inner/outer flange with a straightedge and tape (±1 mm).", notes="Aftermarket retailer statement, not Honda; does not say which 18-in wheel. No Honda source found for offset. Treat as lead."))
add(w, "wheels.bolt_pattern", "Bolt pattern", "text", "medium", R(value="5x114.3", unit="text", cls="C", source_id="d7:kamispeed-11thgen-fitment", locator="article body", evidence="what will work on the 11th Gen Civic with 5x114.3 bolt pattern", as_printed="5x114.3", applicability=db.app("2022+", "US", "11th-gen Civic (generic)", "all", body="all"), confidence="medium", notes="Third-party statement for the generation; no Honda-published value opened."))
for key, desc, unit, imp, hm, srch in [
  ("wheels.center_bore", "Wheel centre bore", "m", "low", "Measure the hub bore with calipers (±0.1 mm), or read the hub pilot diameter.", ["wheel-size.com (403 blocked)", "hondapartsnow rims listings (no bore)", "kamispeed fitment blog (question unanswered)", "query: 11th gen civic center bore 64.1"]),
  ("wheels.lug_torque", "Wheel nut torque", "N*m", "low", "Owner's manual / service information; torque wrench spec in the spare-tire section.", ["owner's manual not opened (techinfo.honda.com treated as blocked)", "hondainfocenter spec page", "press kit"]),
]:
    add(w, key, desc, unit, imp, db.unknown(unit, srch, hm, notes="Lead (unverified): typical Honda 64.1 mm bore / 108 N*m nut torque from recollection; not recorded as a value." if "bore" in key or "torque" in key else ""))
add(w, "wheels.mass", "Mass of one bare wheel", "kg", "high", R(printed=(16.30, "lb"), cls="C", source_id="d7:hondapartsnow-2024-rims", locator="listing 42700-T20-A31, 'Item Weight'", evidence="Item Weight : 16.30 Pounds", as_printed="16.30 Pounds", applicability=db.app("2024", "US", "Sport Touring", "6MT, CVT"), confidence="low", status="estimated", range=[db.units.to_si(16.3, "lb")[0], db.units.to_si(24, "lb")[0]], how_to_measure="Weigh one bare wheel (tire, valve, weights removed) on a scale (±0.1 kg).", notes="Retailer 'Item Weight' field; unreliable: the same site lists a 215/50R17 tire at 4.80 lb. A 18x8 cast wheel is plausibly heavier; upper range bound 24 lb is a judgment, not a source. Treat as weak lead."))
db.save(w)

# ------------------------------------------------------------------ tires
t = mk("tires", "Tires", ["d7:hondanews-ca-2024-hatch-specs", "d7:hondainfocenter-us-2024-hatch-specs", "d7:hondaca-2022-hatch-specpdf", "d7:hondanews-us-2022-hatch-presskit", "d7:tirepressure-2024-civic"])
ev_ca = "All-season tires P235/40 R18 91W P235/40 R18 91W"
loc_ca = "CHASSIS table, row 'All-season tires', Sport Touring column"
ev_us = "All-Season Tires 215/55R16 93H 235/40R18 91W 215/50R17 91H 235/40R18 91W"
loc_us = "Engineering/Chassis table, row 'All-Season Tires', 4th column"
add(t, "tires.size", "Tire size designation", "text", "critical", R(value="P235/40 R18 91W", unit="text", source_id="d7:hondanews-ca-2024-hatch-specs", locator=loc_ca, evidence=ev_ca, as_printed="P235/40 R18 91W", applicability=A24CA, confidence="high"))
add(t, "tires.size", "Tire size designation", "text", "critical", R(value="235/40R18 91W", unit="text", source_id="d7:hondainfocenter-us-2024-hatch-specs", locator=loc_us, evidence=ev_us, as_printed="235/40R18 91W", applicability=A24US, confidence="high"))
for key, desc, pr, ap in [("tires.section_width", "Nominal section width", (235, "mm"), "235"), ("tires.aspect_ratio", "Aspect ratio", (40, "%"), "40"), ("tires.rim_diameter", "Rim diameter code", (18, "in"), "R18")]:
    add(t, key, desc, "m" if key != "tires.aspect_ratio" else "1", "high", R(printed=pr, source_id="d7:hondanews-ca-2024-hatch-specs", locator=loc_ca, evidence=ev_ca, as_printed=ap + " (from P235/40 R18)", applicability=A24CA, confidence="high", notes="Field of the size designation; nominal, not a measured dimension."))
    add(t, key, desc, "m" if key != "tires.aspect_ratio" else "1", "high", R(printed=pr, source_id="d7:hondainfocenter-us-2024-hatch-specs", locator=loc_us, evidence=ev_us, as_printed=ap + " (from 235/40R18)", applicability=A24US, confidence="high"))
add(t, "tires.load_index", "Load index", "count", "medium", R(printed=(91, "count"), source_id="d7:hondanews-ca-2024-hatch-specs", locator=loc_ca, evidence=ev_ca, as_printed="91", applicability=A24CA, confidence="high", notes="91 = 615 kg per tire (standard ETRTO/TRA table; not opened here)."))
add(t, "tires.speed_rating", "Speed rating", "text", "low", R(value="W", unit="text", source_id="d7:hondanews-ca-2024-hatch-specs", locator=loc_ca, evidence=ev_ca, as_printed="W", applicability=A24CA, confidence="high"))
add(t, "tires.type", "Tire type", "text", "high", R(value="all-season", unit="text", source_id="d7:hondanews-ca-2024-hatch-specs", locator=loc_ca, evidence=ev_ca, as_printed="All-season tires", applicability=A24CA, confidence="high", notes=MYCHK))
add(t, "tires.size", "Tire size designation", "text", "critical", R(value="P235/40 R18 91W", unit="text", source_id="d7:hondaca-2022-hatch-specpdf", locator="p.1 CHASSIS, 'All-season tires', Sport Touring column", evidence="All-season tires P215/55 R16 93H P235/40 R18 91W P235/40 R18 91W", as_printed="P235/40 R18 91W", applicability=A22CA, confidence="high"))
add(t, "tires.recommended_pressure_front", "Recommended cold pressure, front", "Pa", "high", R(printed=(33, "psi"), cls="C", source_id="d7:tirepressure-2024-civic", locator="2024 Honda Civic Tire Inflation Chart, row 235/40R18", evidence="235/40R18 33 psi 32 psi Si Sport Hatchback Sport Sedan Sport Touring Hatchback Touring Sedan", as_printed="33 psi", applicability=db.app("2024", "US", "Sport Touring Hatchback (shared row with Sport, Si, Touring sedan)", "unspecified"), confidence="medium", how_to_measure="Read the driver door-jamb tire placard (Canadian placard prints kPa).", notes="Aggregator, not Honda. Owner's manual/placard not opened. Canadian placard value in kPa not found."))
add(t, "tires.recommended_pressure_rear", "Recommended cold pressure, rear", "Pa", "high", R(printed=(32, "psi"), cls="C", source_id="d7:tirepressure-2024-civic", locator="2024 Honda Civic Tire Inflation Chart, row 235/40R18", evidence="235/40R18 33 psi 32 psi Si Sport Hatchback Sport Sedan Sport Touring Hatchback Touring Sedan", as_printed="32 psi", applicability=db.app("2024", "US", "Sport Touring Hatchback (shared row)", "unspecified"), confidence="medium", how_to_measure="Read the driver door-jamb tire placard.", notes="Aggregator, not Honda."))
add(t, "tires.spare_size", "Temporary spare size", "text", "low", R(value="T125/85 D16 99M", unit="text", source_id="d7:hondanews-ca-2024-hatch-specs", locator="CHASSIS table, 'Temporary spare tire'", evidence="Temporary spare tire T125/85 D16 99M T125/85 D16 99M", as_printed="T125/85 D16 99M", applicability=A24CA, confidence="high", notes="US 2024 table prints 'T125/85R16 97M' for Sport Touring: a US/Canada difference in the printed spare designation."))
ts = ["Tire Rack OE search (Akamai 'page unavailable', blocked)", "hondapartsnow 2022 tire listing (no 235/40R18 91W hatch tire listed; only Si Eagle F1 Asymmetric 2 95Y)", "query: 2024 Civic Hatchback Sport Touring original equipment tire 235/40R18 91W", "query: Eagle Sport All-Season OE Honda Civic (retailer text says OE on '2023/2024 Honda Civic' without trim: lead only)", "query: forum stock tires Sport Touring hatch", "goodyear.com / goodyear.ca product pages (404)"]
add(t, "tires.make_model", "OE tire make and model", "text", "high", db.unknown("text", ts, "Photograph the sidewall of a factory tire (brand, model, DOT, any OE marking) and the door placard.", notes="Lead: Goodyear Eagle Sport All-Season 235/40R18 91W is described by retailers as OE on 2023-2024 Honda Civic (trim unstated) - unverified for the hatchback Sport Touring."))
for key, desc, unit, imp in [("tires.oem_variant", "OE marking/variant", "text", "low"), ("tires.overall_diameter", "Maker-published overall diameter of the OE tire", "m", "high"), ("tires.mass", "Tire mass", "kg", "high"), ("tires.tread_depth_new", "New tread depth", "m", "low"), ("tires.utqg", "UTQG", "text", "low"), ("tires.revs_per_km", "Maker-published revolutions per km", "1", "high"), ("tires.test_data", "Independent test data for the OE tire", "text", "medium")]:
    add(t, key, desc, unit, imp, db.unknown(unit, ["blocked on tires.make_model (OE make/model not established)"] + ts[:2], "Identify the OE tire from the sidewall, then read the maker's spec table (overall diameter, revs/km, weight, tread depth, UTQG); weigh one mounted tire minus the bare wheel.", notes="Nominal geometry from the size is derived in scripts/derivations/wheels_tires.py (tires.overall_diameter_nominal, tires.rolling_circumference, tires.loaded_radius)."))
db.save(t)

# ------------------------------------------------------------------ brakes
b = mk("brakes", "Brakes", ["d7:hondanews-ca-2024-hatch-specs", "d7:hondainfocenter-us-2024-hatch-specs", "d7:hondanews-us-2022-hatch-presskit", "d7:hondapartsnow-2024-calipers"])
pk = "All 2022 Civic trims are equipped with 11.1-inch diameter ventilated front brake rotors (0.9-inch rotor thickness) clamped by single-piston brake calipers. The rear disc brakes incorporate 10.2-inch diameter solid rotors (0.4-inch rotor thickness) paired with single-piston calipers."
pkloc = "Chassis section, 'Brake Changes Improve Fuel Efficiency'"
pknote = "Press kit for all 2022 Civic trims; " + "2024 US spec table repeats 11.1/10.2 in for all hatch trims (no model-year change found). Printed to 0.1 in: ±1.3 mm diameter, ±1.3 mm thickness."
usb = "Power-Assisted Ventilated Front Disc/Solid Rear Disc Brakes (front/rear) 11.1 in / 10.2 in 11.1 in / 10.2 in 11.1 in / 10.2 in 11.1 in / 10.2 in"
for key, desc, val, ap in [("brakes.front_rotor_diameter", "Front rotor diameter", 11.1, "11.1-inch"), ("brakes.rear_rotor_diameter", "Rear rotor diameter", 10.2, "10.2-inch")]:
    add(b, key, desc, "m", "high", R(printed=(val, "in"), source_id="d7:hondainfocenter-us-2024-hatch-specs", locator="Chassis table, 'Power-Assisted Ventilated Front Disc/Solid Rear Disc Brakes (front/rear)', 4th column", evidence=usb, as_printed=f"{val} in", applicability=A24US, confidence="high", notes="Canada 2024 table lists the brake type but no sizes."))
    add(b, key, desc, "m", "high", R(printed=(val, "in"), source_id="d7:hondanews-us-2022-hatch-presskit", locator=pkloc, evidence=pk, as_printed=ap, applicability=A22US_ALL, confidence="high", notes=pknote))
add(b, "brakes.front_rotor_thickness", "Front rotor thickness (new)", "m", "medium", R(printed=(0.9, "in"), source_id="d7:hondanews-us-2022-hatch-presskit", locator=pkloc, evidence=pk, as_printed="0.9-inch", applicability=A22US_ALL, confidence="medium", notes=pknote))
add(b, "brakes.rear_rotor_thickness", "Rear rotor thickness (new)", "m", "low", R(printed=(0.4, "in"), source_id="d7:hondanews-us-2022-hatch-presskit", locator=pkloc, evidence=pk, as_printed="0.4-inch", applicability=A22US_ALL, confidence="medium", notes=pknote))
add(b, "brakes.front_rotor_type", "Front rotor type", "text", "medium", R(value="ventilated disc", unit="text", source_id="d7:hondanews-ca-2024-hatch-specs", locator="CHASSIS table", evidence="Power-assisted, ventilated front disc/solid rear disc brakes", as_printed="ventilated front disc", applicability=A24CA, confidence="high"))
add(b, "brakes.rear_rotor_type", "Rear rotor type", "text", "medium", R(value="solid disc", unit="text", source_id="d7:hondanews-ca-2024-hatch-specs", locator="CHASSIS table", evidence="Power-assisted, ventilated front disc/solid rear disc brakes", as_printed="solid rear disc", applicability=A24CA, confidence="high"))
for k, d_ in [("brakes.front_caliper_type", "Front caliper type"), ("brakes.rear_caliper_type", "Rear caliper type")]:
    add(b, k, d_, "text", "medium", R(value="single-piston floating caliper" if "front" in k else "single-piston caliper with electric parking-brake actuator", unit="text", source_id="d7:hondanews-us-2022-hatch-presskit", locator=pkloc, evidence=pk, as_printed="single-piston", applicability=A22US_ALL, confidence="high", notes="'Floating' is an inference from single-piston design (not stated)." if "front" in k else "Actuator: parts catalog lists rear 43018/43019-T20-A02 as 'CALIPER SUB-ASSY; Actuator, Caliper' (see brakes.parking_brake_type)."))
add(b, "brakes.front_pistons", "Front caliper pistons per caliper", "count", "medium", R(printed=(1, "count"), source_id="d7:hondanews-us-2022-hatch-presskit", locator=pkloc, evidence=pk, as_printed="single-piston", applicability=A22US_ALL, confidence="high"))
add(b, "brakes.rear_pistons", "Rear caliper pistons per caliper", "count", "medium", R(printed=(1, "count"), source_id="d7:hondanews-us-2022-hatch-presskit", locator=pkloc, evidence=pk, as_printed="single-piston", applicability=A22US_ALL, confidence="high"))
add(b, "brakes.front_caliper_designation", "Front caliper seal-kit designation in Honda catalog", "text", "low", R(value='AD57-15"', unit="text", cls="C", source_id="d7:hondapartsnow-2024-calipers", locator="listing 01463-TXM-A01", evidence='2024 Honda Civic Set, Front (Ad57-15")', as_printed='Ad57-15"', applicability=db.app("2024", "US", "fits incl. 5 Door 1.5T Sport Touring", "6MT, CVT"), confidence="medium", notes="Front caliper seal kit 01463-TXM-A01 fits 5 Door 1.5T Sport Touring 6MT/CVT. Honda caliper codes of this form are commonly read as piston diameter in mm (57) and minimum wheel size (15 in) - that reading is a lead, not confirmed."))
psearch = ["hondanews.com 2022 press kit (says single-piston, no bore)", "hondainfocenter 2024 specs", "hondapartsnow caliper listing (front seal kit 'Ad57-15\"' designation only)", "buybrakes.com (403)", "query: Civic 2022 caliper piston diameter"]
add(b, "brakes.front_piston_diameter", "Front caliper piston diameter", "m", "high", db.unknown("m", psearch, "Measure the front caliper piston OD with calipers (±0.1 mm) during a pad change.", notes="Lead: 57 mm from the 'AD57-15\"' seal-kit designation (unconfirmed reading)."))
add(b, "brakes.rear_piston_diameter", "Rear caliper piston diameter", "m", "high", db.unknown("m", psearch, "Measure the rear caliper piston OD with calipers (±0.1 mm) during a pad change."))
add(b, "brakes.booster_type", "Brake booster type", "text", "medium", db.unknown("text", ["Honda Canada 2024 spec ('Power-assisted')", "US 2024 spec ('Power-Assisted')", "2022 press kit chassis section (no booster type)"], "Look at the firewall behind the master cylinder: vacuum booster with hose from intake/pump vs electric booster; photograph.", notes="Only 'Power-assisted' is published."))
add(b, "brakes.abs", "4-wheel ABS", "bool", "low", R(value=True, unit="bool", source_id="d7:hondanews-ca-2024-hatch-specs", locator="ACTIVE SAFETY table", evidence="4-wheel Anti-lock Braking System", as_printed="•", applicability=A24CA, confidence="high"))
add(b, "brakes.ebd", "Electronic brake-force distribution", "bool", "low", R(value=True, unit="bool", source_id="d7:hondanews-ca-2024-hatch-specs", locator="ACTIVE SAFETY table", evidence="Electronic Brake-force Distribution (EBD)", as_printed="•", applicability=A24CA, confidence="high"))
add(b, "brakes.brake_assist", "Brake assist", "bool", "low", R(value=True, unit="bool", source_id="d7:hondanews-ca-2024-hatch-specs", locator="ACTIVE SAFETY table", evidence="Brake Assist", as_printed="•", applicability=A24CA, confidence="high"))
add(b, "brakes.parking_brake_type", "Parking brake type", "text", "medium", R(value="electric parking brake (EPB) with automatic brake hold; rear caliper-mounted actuator", unit="text", source_id="d7:hondanews-ca-2024-hatch-specs", locator="CHASSIS table", evidence="Electronic Parking Brake (EPB) with automatic brake hold", as_printed="Electronic Parking Brake (EPB) with automatic brake hold", applicability=A24CA, confidence="high", notes="Rear caliper actuator: hondapartsnow lists 43018-T20-A02 'CALIPER SUB-ASSY; Actuator, Caliper' fitting 5 Door 1.5T Sport Touring. Manual cars: press kit says parking brake button is left of the shifter."))
add(b, "brakes.pad_mu", "Pad friction coefficient", "1", "medium", db.unknown("1", ["no published OE pad mu found", "press kit"], "Not directly measurable at home; use OE pad edge code (e.g. FF) from a pad photo.", notes="Bias derivation assumes equal mu front/rear."))
db.save(b)

# ------------------------------------------------------------------ aero
a = mk("aero", "Aerodynamics", ["d7:hondanews-ca-2024-hatch-specs", "d7:hondanews-us-2022-hatch-presskit"])
aer = "Careful tuning of its design has given the 11th-generation Civic Hatchback outstanding aerodynamic performance, including a drag reduction of approximately 3 percent."
add(a, "aero.cd", "Drag coefficient", "1", "high", db.unknown("1", ["2022 hatch press kit 'Aerodynamic Performance' (only '~3 percent' reduction, no Cd)", "hondainfocenter 2024 spec table (no Cd)", "hondanews.ca 2024 spec (no Cd)", "query: 2022 Civic Hatchback drag coefficient press release", "query: 11th generation Civic hatchback drag coefficient Cd official"], "Coast-down test (two directions, calm day, known mass) fitted to F = A + B v + C v^2 gives CdA; or EPA coast-down target coefficients if found.", notes="A search summary mentioned '0.29' for the 2024 hatch without a source page; not recorded. Press kit: " + aer))
add(a, "aero.drag_reduction_note", "Published aero statement", "text", "low", R(value="drag reduced ~3 percent vs 10th-gen hatchback", unit="text", source_id="d7:hondanews-us-2022-hatch-presskit", locator="Exterior: 'Aerodynamic Performance'", evidence=aer, as_printed="approximately 3 percent", applicability=db.app("2022", "US", "all hatchback trims", "all"), confidence="high"))
add(a, "aero.spoiler", "Rear spoiler", "text", "medium", R(value="no separate wing; spoiler integrated into the resin hatch/tailgate trailing edge", unit="text", source_id="d7:hondanews-us-2022-hatch-presskit", locator="Exterior Design 'What's New' and body text", evidence="Distinct styling cues include a honeycomb grille, a unique integrated rear spoiler, exhaust finishers and standard alloy wheels … The 2022 Civic Hatchback eliminates the previous rear spoiler, giving the rear end a much cleaner and more integrated appearance without any loss of visibility.", as_printed="integrated rear spoiler", applicability=db.app("2022", "US", "all hatchback trims", "all"), confidence="high", notes="HPD accessory tailgate spoiler is an option, not stock. 2024 Canadian spec lists no spoiler item."))
add(a, "aero.underbody", "Underbody covers", "text", "medium", R(value="floor undercover present (described for noise absorption); extent not published", unit="text", source_id="d7:hondanews-us-2022-hatch-presskit", locator="Interior/NVH section", evidence="Road noise is reduced through the use of a noise-absorbing floor undercover and rear inner fender liner, plus noise-absorbing carpeting.", as_printed="noise-absorbing floor undercover", applicability=db.app("2022", "US", "all hatchback trims", "all"), confidence="medium", how_to_measure="Underbody photos on a lift showing engine undercover and floor panels.", status="confirmed"))
add(a, "aero.features", "Published aero detail features", "text", "low", R(value="reshaped front bumper corners; larger A-pillar drip molding; vortex generators under mirror housings; optimised tailgate trailing-edge height; taillights shaped to reduce trailing vortex", unit="text", source_id="d7:hondanews-us-2022-hatch-presskit", locator="Exterior: 'Aerodynamic Performance'", evidence="In front, a new and better bumper corner shape was used … airflow turbulence under the door mirror was reduced by adding small vortex generators to the underside of the door mirror housing. In the rear, the height of the trailing edge of the tailgate is optimized to reduce downwash.", as_printed="", applicability=db.app("2022", "US", "all hatchback trims", "all"), confidence="high"))
for key, desc, unit, imp, hm in [
  ("aero.frontal_area", "Frontal area (published)", "m2", "high", "Photograph the car head-on with a long lens next to a scale bar and integrate the silhouette by script."),
  ("aero.active_grille_shutter", "Active grille shutter", "bool", "low", "Look behind the lower grille for shutter vanes (photo with flashlight)."),
  ("aero.cooling_openings", "Cooling opening areas", "m2", "low", "Front photos scaled by wheelbase; measure open grille areas by script."),
  ("aero.lift_front", "Front lift coefficient", "1", "medium", "Not measurable without a wind tunnel; leave unknown."),
  ("aero.lift_rear", "Rear lift coefficient", "1", "medium", "Not measurable without a wind tunnel; leave unknown."),
  ("aero.balance", "Aero balance", "1", "low", "Not measurable without a wind tunnel."),
]:
    add(a, key, desc, unit, imp, db.unknown(unit, ["2022 hatch press kit (aero section)", "hondanews.ca 2024 spec", "hondainfocenter 2024 spec", "query: Civic hatchback drag coefficient / aerodynamics"], hm, notes="Not published. Frontal-area estimate from width x height is derived in scripts/derivations/brakes_aero.py (aero.frontal_area_est)." if key == "aero.frontal_area" else "Not published by Honda in sources opened."))
db.save(a)
print("ok")
