#!/usr/bin/env python3
"""Evaluate every registered derivation (scripts/derivations/*.py) from resolved inputs.

Writes vehicle_data/derived.json (class D/E records with module, function, inputs and
input values) and the CSV tables registered in TABLES. Inputs come from the resolution
of all non-derived files (user measurements first); a derivation never overrides a key
that already resolves from a sourced record — its output is just another candidate.

Usage: python3 scripts/derive.py            (then re-run resolve.py)
       evaluate() is also used by validate_db.py to recompute and compare.
"""
import csv
import importlib
import inspect
import json
import os
import pkgutil
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import dbutil  # noqa: E402
import resolve  # noqa: E402

ROOT = dbutil.ROOT
OUT = os.path.join(dbutil.DATA, "derived.json")


def load_modules():
    import derivations
    mods = []
    for m in sorted(pkgutil.iter_modules(derivations.__path__), key=lambda m: m.name):
        mods.append(importlib.import_module(f"derivations.{m.name}"))
    return mods


def _src(fn):
    try:
        return inspect.getsource(fn).strip()
    except (OSError, TypeError):
        return repr(fn)


def evaluate():
    """Return (derived_domain_dict, tables) computed from current base resolution."""
    params, _ = resolve.load_all(include_derived=False)
    base, _ = resolve.resolve(params)
    values = {k: v["value"] for k, v in base.items() if v["value"] is not None}
    mods = load_modules()
    ders = [(m, d) for m in mods for d in getattr(m, "DERIVATIONS", [])]
    tables = [(m, t) for m in mods for t in getattr(m, "TABLES", [])]
    out = {"domain": "derived", "title": "Derived values (generated by scripts/derive.py — do not edit)",
           "schema_version": 1, "sources": {}, "parameters": {}, "tables": []}
    done, pending = set(), list(ders)
    for _ in range(len(ders) + 1):
        progressed, still = False, []
        for m, d in pending:
            ins = d.get("inputs", {})
            missing = [p for p in ins.values() if p not in values]
            # wait for inputs another derivation may still produce
            if missing and any(p in {dd["key"] for _, dd in pending if dd is not d} for p in missing):
                still.append((m, d))
                continue
            progressed = True
            done.add(d["key"])
            deriv = {"module": m.__name__.replace("derivations.", "scripts/derivations/") + ".py",
                     "function": _src(d["fn"]), "inputs": ins,
                     "input_values": {a: values.get(p) for a, p in ins.items()},
                     "basis_sources": d.get("basis_sources", [])}
            if missing:
                rec = dbutil.record(value=None, unit=d["unit"], status="unknown", cls=None,
                                    confidence="none", how_to_measure=d.get("how_to_measure", ""),
                                    notes=f"Not computable: missing inputs {missing}. " + d.get("notes", ""),
                                    derivation=deriv, searches=["derivation inputs unresolved"])
            else:
                kw = {a: values[p] for a, p in ins.items()}
                try:
                    val = d["fn"](**kw)
                    rng = d["range_fn"](**kw) if d.get("range_fn") else None
                except Exception as e:  # report, don't hide
                    val, rng = None, None
                    deriv["error"] = f"{type(e).__name__}: {e}"
                if val is None:
                    rec = dbutil.record(value=None, unit=d["unit"], status="unknown", cls=None,
                                        confidence="none", how_to_measure=d.get("how_to_measure", ""),
                                        notes="Derivation returned no value. " + d.get("notes", ""),
                                        derivation=deriv, searches=["derivation failed"])
                else:
                    if rng is None:
                        rng = [val, val] if isinstance(val, (int, float)) else None
                    rec = dbutil.record(value=val, unit=d["unit"], status=d.get("status", "estimated"),
                                        cls=d.get("cls", "D"), source_id=None, locator=deriv["module"],
                                        evidence="", as_printed="", applicability={"notes": "this car (derived)"},
                                        confidence=d.get("confidence", "medium"), range=rng,
                                        how_to_measure=d.get("how_to_measure"), notes=d.get("notes", ""),
                                        derivation=deriv)
                    if d["key"] not in values:
                        values[d["key"]] = val
            out["parameters"][d["key"]] = {"description": d.get("description", ""), "unit": d["unit"],
                                           "impact": d.get("impact", "medium"), "candidates": [rec]}
        pending = still
        if not pending or not progressed:
            break
    for m, d in pending:  # dependency cycle
        out["parameters"][d["key"]] = {"description": d.get("description", ""), "unit": d["unit"],
                                       "impact": d.get("impact", "medium"),
                                       "candidates": [dbutil.unknown(d["unit"], ["dependency cycle"],
                                                                     d.get("how_to_measure", ""))]}
    built = []
    for m, t in tables:
        ins = t.get("inputs", {})
        missing = [p for p in ins.values() if p not in values]
        entry = {"path": t["path"], "module": m.__name__, "description": t.get("description", ""),
                 "inputs": ins, "input_values": {a: values.get(p) for a, p in ins.items()},
                 "missing_inputs": missing, "rows": None}
        if not missing:
            try:
                entry["rows"] = t["fn"](**{a: values[p] for a, p in ins.items()})
            except Exception as e:
                entry["error"] = f"{type(e).__name__}: {e}"
        built.append(entry)
    return out, built


def write_tables(built):
    meta = []
    for t in built:
        path = os.path.join(ROOT, t["path"])
        m = {k: v for k, v in t.items() if k != "rows"}
        if t["rows"]:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            cols = list(t["rows"][0].keys())
            with open(path, "w", newline="", encoding="utf-8") as f:
                w = csv.DictWriter(f, fieldnames=cols)
                w.writeheader()
                for r in t["rows"]:
                    w.writerow(r)
            m["n_rows"] = len(t["rows"])
        else:
            m["n_rows"] = 0
        meta.append(m)
    return meta


def main():
    out, built = evaluate()
    out["tables"] = write_tables(built)
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2, ensure_ascii=False, default=str)
        f.write("\n")
    n = len(out["parameters"])
    nu = sum(1 for p in out["parameters"].values() if p["candidates"][0]["value"] is None)
    print(f"derived {n} values ({nu} not computable), {sum(1 for t in out['tables'] if t['n_rows'])}/"
          f"{len(out['tables'])} tables written -> {os.path.relpath(OUT, ROOT)}")
    for t in out["tables"]:
        if not t["n_rows"]:
            print(f"  table {t['path']} not built: missing {t['missing_inputs']} {t.get('error', '')}")


if __name__ == "__main__":
    main()
