#!/usr/bin/env python3
"""Generate reports from the database so they cannot drift from it:
SOURCES.md, docs/PHASE1_REPORT.md, docs/CONFLICTS.md, docs/UNCERTAINTIES.md,
docs/PHASE1_SCORECARD.md (verdict lines from docs/scorecard_input.json; counts computed here).

Run after resolve.py, derive.py, resolve.py, validate_db.py --json cache/validate.json.
"""
import glob
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import crosschecks  # noqa: E402
import dbutil  # noqa: E402
import resolve  # noqa: E402

ROOT = dbutil.ROOT
DOCS = os.path.join(ROOT, "docs")
GEN = "<!-- Generated by scripts/make_report.py from vehicle_data/ — do not edit by hand. -->\n\n"

DOMAINS = [
    (1, "Identity", ["identity."]),
    (2, "Dimensions", ["dimensions.", "proportions."]),
    (3, "Mass and inertia", ["mass."]),
    (4, "Engine and turbo", ["engine.", "turbo."]),
    (5, "Drivetrain", ["transmission.", "drivetrain."]),
    (6, "Steering and suspension", ["steering.", "suspension.", "alignment.", "hardpoints."]),
    (7, "Wheels, tires, brakes and aero", ["wheels.", "tires.", "brakes.", "aero."]),
    (8, "Performance targets", ["perf."]),
    (9, "Visual references, paint and cluster", ["paint.", "dashboard.", "references."]),
    (10, "Audio", ["audio."]),
    (11, "Platform", ["platform."]),
]
IMPACT = {"critical": 0, "high": 1, "medium": 2, "low": 3}


def domain_of(key):
    for n, name, pre in DOMAINS:
        if any(key.startswith(p) for p in pre):
            return n
    return 99


def fmt(v, unit):
    if v is None:
        return "—"
    if isinstance(v, bool):
        return str(v).lower()
    if isinstance(v, float):
        s = f"{v:.6g}"
    elif isinstance(v, list):
        s = "[" + ", ".join(f"{x:.4g}" if isinstance(x, float) else str(x) for x in v[:6]) + \
            (", …" if len(v) > 6 else "") + "]"
    else:
        s = str(v)
    s = s.replace("|", "/").replace("\n", " ")
    if len(s) > 90:
        s = s[:87] + "…"
    return s if unit in (None, "", "text", "1", "bool") else f"{s} {unit}"


def load():
    res = json.load(open(resolve.OUT))
    params, sources = resolve.load_all()
    return res["parameters"], res["conflicts"], params, sources


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    print("wrote", os.path.relpath(path, ROOT))


def sources_md(sources, params):
    used = {}
    for k, e in params.items():
        for f, i, r in e["cands"]:
            if r.get("source_id"):
                used.setdefault(r["source_id"], set()).add(k)
    lines = ["# Sources", "", GEN.strip(), "",
             f"{len(sources)} registered sources; {len(used)} cited by at least one record. "
             "Class is the source's default class (A manufacturer/government, B measurement, "
             "C reputable third party, D–F derived/estimate/fallback). Accessed dates are when the page "
             "was opened for this database.", ""]
    for n, name, pre in DOMAINS + [(99, "Other", [])]:
        rows = [(sid, s) for sid, s in sorted(sources.items())
                if (domain_of(next(iter(sorted(used.get(sid, {"zz"}))))) == n)]
        if not rows:
            continue
        lines += [f"## {n if n != 99 else ''} {name}".replace("##  ", "## "), "",
                  "| id | class | title / publisher | accessed | cited by |", "|---|---|---|---|---|"]
        for sid, s in rows:
            t = (s.get("title") or "").replace("|", "/")
            url = s.get("url") or ""
            link = f"[{t}]({url})" if url else t
            lines.append(f"| `{sid}` | {s.get('class')} | {link} — {s.get('publisher','')} | "
                         f"{s.get('accessed','')} | {len(used.get(sid, []))} |")
        lines.append("")
    return "\n".join(lines) + "\n"


def report_md(res, conflicts, params, sources, val):
    L = ["# Phase 1 report — 2024 Civic Hatchback Sport Touring 6MT (Canada)", "", GEN.strip(), "",
         "Each row is the **effective** record chosen by `scripts/resolve.py` (precedence: user "
         "measurement > A > B/C > D > E > F; then closest applicability to 2024 / Canada / Sport Touring / "
         "6MT). `n` = number of candidate records kept. Class: A manufacturer/government, B measurement, "
         "C third party, D derived by script, E engineering estimate, F fallback. Status `unknown` means "
         "not found after the primary sources and ~5 searches; see `docs/UNCERTAINTIES.md`.", ""]
    tot = len(res)
    by_status = {}
    for r in res.values():
        by_status[r["status"]] = by_status.get(r["status"], 0) + 1
    by_class = {}
    for r in res.values():
        by_class[str(r["class"])] = by_class.get(str(r["class"]), 0) + 1
    L += [f"**{tot} parameters**: " + ", ".join(f"{v} {k}" for k, v in sorted(by_status.items())) +
          ". By class: " + ", ".join(f"{k}: {v}" for k, v in sorted(by_class.items())) +
          f". Conflicts: {len(conflicts)} (see `docs/CONFLICTS.md`).", ""]
    if val:
        L += ["## Validation", "",
              f"`scripts/validate_db.py`: **{len(val['errors'])} errors, {len(val['warnings'])} warnings**; "
              f"{val['quotes_checked_against_cache']} evidence quotes re-found in cached page text, "
              f"{val['quotes_not_found']} not found (listed as warnings).", "",
              "| cross-check | result | detail |", "|---|---|---|"]
        for c in val["crosschecks"]:
            L.append(f"| {c['name']} | {c['status']} | {c['detail'].replace('|', '/')} |")
        L.append("")
    for n, name, pre in DOMAINS:
        keys = sorted(k for k in res if domain_of(k) == n)
        L += [f"## {n}. {name}", ""]
        log = glob.glob(os.path.join(DOCS, "research_log", f"{n:02d}_*.md"))
        if log:
            L.append(f"Research log: `{os.path.relpath(log[0], ROOT)}`.")
            L.append("")
        if not keys:
            L += ["_No parameter records in the database for this domain._", ""]
            continue
        L += ["| parameter | value | status | class | conf. | source | n |", "|---|---|---|---|---|---|---|"]
        for k in keys:
            r = res[k]
            v = fmt(r["value"], r["unit"])
            if r.get("range") and r["class"] in ("D", "E", "F") and all(isinstance(x, (int, float)) for x in r["range"]):
                v += f" (range {fmt(r['range'][0], '')}–{fmt(r['range'][1], '')})"
            flag = " ⚠" if r.get("conflict") else ""
            L.append(f"| `{k}`{flag} | {v} | {r['status']} | {r['class'] or '—'} | {r['confidence']} | "
                     f"{('`'+r['source_id']+'`') if r.get('source_id') else ('derived' if r['class']=='D' else '—')} | "
                     f"{r['n_candidates']} |")
        L.append("")
    return "\n".join(L) + "\n"


def conflicts_md(conflicts):
    L = ["# Conflicts between credible sources", "", GEN.strip(), "",
         "Listed when two or more user/A/B/C candidates for the same parameter differ by more than 1 % "
         "(numbers) or textually. Both candidates are kept in the data files; the selected one is what "
         "`scripts/resolve.py` chose and why. Many numeric conflicts are rounding between metric and "
         "imperial printings; those are still listed so nothing is averaged silently.", ""]
    if not conflicts:
        L.append("_None._")
    for c in conflicts:
        s = c["selected"]
        L += [f"## `{c['key']}`", "",
              f"- **Selected:** {fmt(s['value'], s['unit'])} — class {s['class']}, `{s['source_id']}` "
              f"({json.dumps(s.get('applicability'), ensure_ascii=False)})"]
        if s.get("selection_reason"):
            L.append(f"  - reason given: {s['selection_reason']}")
        for o in c["others"]:
            L.append(f"- Other: {fmt(o['value'], o['unit'])} — class {o['class']}, `{o['source_id']}` "
                     f"({json.dumps(o.get('applicability'), ensure_ascii=False)})")
        L += [f"- Rule: {c['rule']}", ""]
    return "\n".join(L) + "\n"


def uncertainties_md(res, params):
    rows = []
    for k, r in res.items():
        if r["status"] in ("estimated", "unknown") or r["class"] in ("D", "E", "F"):
            if r["status"] == "confirmed" and r["class"] == "D":
                continue  # exact arithmetic on confirmed inputs
            e = params.get(k, {})
            cand = None
            for f, i, c in e.get("cands", []):
                if f == r["file"] and i == r["candidate_index"]:
                    cand = c
            rows.append((IMPACT.get(r.get("impact"), 4), 0 if r["status"] == "unknown" else 1,
                         {"F": 0, "E": 1, "D": 2}.get(r["class"], 3), k, r, cand or {}))
    rows.sort(key=lambda x: x[:4])
    L = ["# Uncertainties", "", GEN.strip(), "",
         "Every effective value that is estimated or unknown, ordered by how much it affects the finished "
         "car (impact assigned per parameter by the researching thread: critical > high > medium > low), "
         "then unknown before estimated. `how to measure` says how to retire it; ranked capture work is in "
         "`docs/CAPTURE_REQUESTS.md`.", "",
         f"{len(rows)} entries.", "",
         "| # | impact | parameter | status | class | value (range) | how to measure |", "|---|---|---|---|---|---|---|"]
    for n, (_, _, _, k, r, c) in enumerate(rows, 1):
        v = fmt(r["value"], r["unit"])
        if r.get("range") and all(isinstance(x, (int, float)) for x in r["range"]):
            v += f" ({fmt(r['range'][0], '')}–{fmt(r['range'][1], '')})"
        htm = (c.get("how_to_measure") or "").replace("|", "/").replace("\n", " ")
        if len(htm) > 160:
            htm = htm[:157] + "…"
        L.append(f"| {n} | {r.get('impact')} | `{k}` | {r['status']} | {r['class'] or '—'} | {v} | {htm} |")
    return "\n".join(L) + "\n"


def scorecard_md(res, val, params):
    inp_path = os.path.join(DOCS, "scorecard_input.json")
    inp = json.load(open(inp_path)) if os.path.exists(inp_path) else {}
    hp = {"confirmed": 0, "estimated": 0, "unknown": 0}
    for k, r in res.items():
        if k.startswith("hardpoints."):
            hp[r["status"]] = hp.get(r["status"], 0) + 1
    dyno = sorted(glob.glob(os.path.join(ROOT, "engine_curves", "*.json")))
    L = ["# Phase 1 scorecard", "", GEN.strip(), "",
         "Verdicts are judgments recorded in `docs/scorecard_input.json`; every count below is computed "
         "from the database. An honest FAIL is acceptable; an unsupported PASS is not.", "",
         "| # | domain | verdict | evidence |", "|---|---|---|---|"]
    for n, name, pre in DOMAINS:
        keys = [k for k in res if domain_of(k) == n]
        nconf = sum(1 for k in keys if res[k]["status"] == "confirmed")
        nest = sum(1 for k in keys if res[k]["status"] == "estimated")
        nunk = sum(1 for k in keys if res[k]["status"] == "unknown")
        d = inp.get(str(n), {})
        ev = d.get("evidence", "")
        L.append(f"| {n} | {name} | **{d.get('verdict', 'NOT ASSESSED')}** | {ev} "
                 f"(records: {nconf} confirmed, {nest} estimated, {nunk} unknown) |")
    L += ["", "## Counts", "",
          f"- Hard points: **{hp.get('confirmed',0)} confirmed, {hp.get('estimated',0)} estimated, "
          f"{hp.get('unknown',0)} unknown**.",
          f"- Stock dyno sources in `engine_curves/`: **{len(dyno)}**" +
          (": " + ", ".join(f"`{os.path.basename(p)}`" for p in dyno) if dyno else "") + ".",
          f"- User's reference clip (youtube.com/shorts/BDuJz3FTOpU): **{inp.get('clip', 'not assessed')}**."]
    if val:
        L.append(f"- Validation: {len(val['errors'])} errors, {len(val['warnings'])} warnings; "
                 + ", ".join(f"{c['name']}: {c['status']}" for c in val["crosschecks"]) + ".")
    for extra in inp.get("notes", []):
        L.append(f"- {extra}")
    return "\n".join(L) + "\n"


def main():
    res, conflicts, params, sources = load()
    vpath = os.path.join(ROOT, "cache", "validate.json")
    val = json.load(open(vpath)) if os.path.exists(vpath) else None
    write(os.path.join(ROOT, "SOURCES.md"), sources_md(sources, params))
    write(os.path.join(DOCS, "PHASE1_REPORT.md"), report_md(res, conflicts, params, sources, val))
    write(os.path.join(DOCS, "CONFLICTS.md"), conflicts_md(conflicts))
    write(os.path.join(DOCS, "UNCERTAINTIES.md"), uncertainties_md(res, params))
    write(os.path.join(DOCS, "PHASE1_SCORECARD.md"), scorecard_md(res, val, params))


if __name__ == "__main__":
    main()
