#!/usr/bin/env python3
"""Re-open the live source page of the twenty values that matter most and confirm the
verbatim evidence is really on it. Writes docs/SPOT_CHECK.md and cache/spot_check.json.
A value whose quote cannot be re-found is reported FAIL so it can be fixed or downgraded."""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import dbutil  # noqa: E402
import resolve  # noqa: E402
from fetch_page import fetch_static, fetch_rendered, html_to_text, robots_allowed  # noqa: E402
from validate_db import norm  # noqa: E402

KEYS = ["mass.curb_mass", "mass.front_fraction", "engine.power_max", "engine.torque_max", "engine.redline_rpm",
        "transmission.gear_1", "transmission.gear_6", "transmission.final_drive", "tires.size", "wheels.width",
        "brakes.front_rotor_diameter", "dimensions.wheelbase", "dimensions.track_front", "dimensions.track_rear",
        "dimensions.length", "dimensions.height", "steering.ratio_overall", "steering.turning_circle_diameter",
        "suspension.arb_front_diameter", "perf.accel_0_60mph"]


def live_text(url, cache):
    if url in cache:
        return cache[url]
    ok, detail = robots_allowed(url)
    if not ok:
        cache[url] = (None, detail)
        return cache[url]
    texts = []
    try:
        st, _, html = fetch_static(url)
        texts.append(html_to_text(html))
        texts.append(html)
    except Exception as e:
        st = f"static error {type(e).__name__}"
    try:
        st2, _, html2, txt2 = fetch_rendered(url, 5000)
        texts += [txt2, html_to_text(html2)]
    except Exception as e:
        st2 = f"render error {type(e).__name__}"
    cache[url] = (norm(" ".join(texts)), f"static {st}, rendered {st2}")
    return cache[url]


def main():
    res = json.load(open(resolve.OUT))["parameters"]
    params, sources = resolve.load_all()
    cache, rows = {}, []
    for k in KEYS:
        r = res.get(k)
        row = {"key": k}
        if not r or r["value"] is None:
            row.update(result="FAIL", why="no resolved value")
            rows.append(row)
            continue
        cand = next(c for f, i, c in params[k]["cands"] if f == r["file"] and i == r["candidate_index"])
        src = sources.get(cand.get("source_id"), {})
        row.update(value=r["value"], unit=r["unit"], cls=r["class"], conf=r["confidence"],
                   source_id=cand.get("source_id"), url=src.get("url"), evidence=cand.get("evidence"),
                   as_printed=cand.get("as_printed"), locator=cand.get("locator"))
        if r["class"] not in ("A", "B", "C") or not src.get("url"):
            row.update(result="FAIL", why=f"effective record is class {r['class']} without a live source")
            rows.append(row)
            continue
        hay, how = live_text(src["url"], cache)
        if hay is None:
            row.update(result="NOT CHECKED", why=how)
        else:
            frags = [f for f in re.split(r"\s*(?:…|\.\.\.)\s*", cand["evidence"]) if f.strip()]
            missing = [f for f in frags if norm(f) not in hay]
            row.update(result="PASS" if not missing else "FAIL", why=how +
                       ("" if not missing else f"; not found: {missing[0][:80]!r}"))
        rows.append(row)
        print(f"{row['result']:12} {k}: {row.get('why')}")
    json.dump(rows, open(os.path.join(dbutil.ROOT, "cache", "spot_check.json"), "w"), indent=2, default=str)
    L = ["# Spot check — twenty values that matter most", "",
         "<!-- Generated by scripts/spot_check.py — do not edit by hand. -->", "",
         "Each source page was re-opened live by `scripts/spot_check.py` (plain fetch and headless render) on the "
         "date of this run, and the recorded verbatim quote was searched for in the page text "
         "(whitespace/punctuation-normalised). FAIL means the quote was not found and the record must be fixed or "
         "downgraded.", "",
         f"Result: **{sum(r['result']=='PASS' for r in rows)} PASS, {sum(r['result']=='FAIL' for r in rows)} FAIL, "
         f"{sum(r['result']=='NOT CHECKED' for r in rows)} not checked** of {len(rows)}.", ""]
    for n, r in enumerate(rows, 1):
        v = r.get("value")
        L += [f"## {n}. `{r['key']}` — {r['result']}", "",
              f"- Value: {v} {r.get('unit','')} (as printed: {r.get('as_printed')}); class {r.get('cls')}, "
              f"confidence {r.get('conf')}",
              f"- Source: `{r.get('source_id')}` — {r.get('url')}",
              f"- Locator: {r.get('locator')}",
              f"- Quote: \"{(r.get('evidence') or '')[:400]}\"",
              f"- Re-check: {r.get('why')}", ""]
    open(os.path.join(dbutil.ROOT, "docs", "SPOT_CHECK.md"), "w").write("\n".join(L) + "\n")
    print("wrote docs/SPOT_CHECK.md")


if __name__ == "__main__":
    main()
